# Numpy Lib

In [2]:
import numpy as np

In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]


In [14]:
arr.reshape(2,-1)

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [34]:
#reshpe in array in the 3D Array 
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[7,8,9]])
arr.reshape(2,6)
print(arr)
arr.ndim # gives original array dimension

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]


2

In [28]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[7,8,9]])

In [30]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]


In [38]:
#indexinig 
arr[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [42]:
arr=np.array([[1,2,3],[2,3,4],[2,6,5],[7,8,9]])
arr.reshape(2,6)

array([[1, 2, 3, 2, 3, 4],
       [2, 6, 5, 7, 8, 9]])

In [56]:
arr=np.array([[1,2,3],[2,3,4],[2,6,5],[7,8,9]])
# arr.reshape(2,6)
print(arr)

[[1 2 3]
 [2 3 4]
 [2 6 5]
 [7 8 9]]


In [58]:
arr[2,1]

6

In [66]:
import numpy as np
arr=np.array([[1,2,3],[2,3,4],[2,6,5]])
np.linalg.inv(arr)

array([[-1.8,  1.6, -0.2],
       [-0.4, -0.2,  0.4],
       [ 1.2, -0.4, -0.2]])

In [70]:
arr=np.array([1,3,3,3,3,3,3,3,3])
np.unique(arr)

array([1, 3])